env:
  browser: true
  es2021: true
  node: true
  jest: true
extends:
  - plugin:react/recommended
  - react-app
overrides: []
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
  project: './tsconfig.json'
plugins:
  - react
rules: {}
